version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: eventhub_db
    environment:
      POSTGRES_DB: eventhub
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
